/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cursoemvideo.bhaskara;

/**
 *
 * @author Gabizinha
 */
public class BhaskaraTela extends javax.swing.JFrame {

    /**
     * Creates new form BhaskaraTela
     */
    public BhaskaraTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCoeficienteA = new javax.swing.JSpinner();
        txtCoeficienteB = new javax.swing.JSpinner();
        txtCoeficienteC = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        lblCoeficienteA = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCoeficienteB = new javax.swing.JLabel();
        lblCoeficienteC = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblDelta = new javax.swing.JLabel();
        btnDelta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCoeficienteA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCoeficienteA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCoeficienteAStateChanged(evt);
            }
        });

        txtCoeficienteB.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCoeficienteB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCoeficienteBStateChanged(evt);
            }
        });

        txtCoeficienteC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCoeficienteC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtCoeficienteCStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Δ =");

        lblCoeficienteA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCoeficienteA.setForeground(new java.awt.Color(255, 0, 0));
        lblCoeficienteA.setText("B²");

        jLabel3.setText("-");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("4");

        lblCoeficienteB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCoeficienteB.setForeground(new java.awt.Color(255, 0, 0));
        lblCoeficienteB.setText("A");

        lblCoeficienteC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCoeficienteC.setForeground(new java.awt.Color(255, 51, 51));
        lblCoeficienteC.setText("C");

        btnDelta.setText("Calcular Delta Δ ");
        btnDelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeltaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("x²+");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("x+");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("= 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCoeficienteA)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCoeficienteB)
                                .addGap(18, 18, 18)
                                .addComponent(lblCoeficienteC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCoeficienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCoeficienteB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCoeficienteC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDelta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoeficienteB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(txtCoeficienteA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCoeficienteC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoeficienteA)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoeficienteB)
                    .addComponent(lblCoeficienteC)
                    .addComponent(btnDelta)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDelta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeltaActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(txtCoeficienteB.getValue().toString());
        int b = Integer.parseInt(txtCoeficienteA.getValue().toString());
        int c = Integer.parseInt(txtCoeficienteC.getValue().toString());
        lblCoeficienteB.setText(Integer.toString(b));
        lblCoeficienteA.setText(Integer.toString(a));
        lblCoeficienteC.setText(Integer.toString(c));
        double delta =Math.pow(b, 2) - 4 * b * c;
        lblDelta.setText(String.format("%.1f", delta));
        if (delta > 0 && delta == 0) {
            lblDelta.setText("<html><strong>Δ = " + delta + "</strong></html>");
            lblTipo.setText("<html>Tipo = Existem raízes reais</html>");
        } else if (delta < 0) {
                        lblDelta.setText("<html><strong>Δ = " + delta + "</strong></html>");
            lblTipo.setText("<html>Tipo = Não existem raízes reais</html>" );

        }

    }//GEN-LAST:event_btnDeltaActionPerformed

    private void txtCoeficienteAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCoeficienteAStateChanged
        // TODO add your handling code here:
        lblCoeficienteA.setText(txtCoeficienteA.getValue().toString());
    }//GEN-LAST:event_txtCoeficienteAStateChanged

    private void txtCoeficienteBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCoeficienteBStateChanged
        // TODO add your handling code here:
                lblCoeficienteB.setText(txtCoeficienteB.getValue().toString());

    }//GEN-LAST:event_txtCoeficienteBStateChanged

    private void txtCoeficienteCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtCoeficienteCStateChanged
        // TODO add your handling code here:
        lblCoeficienteC.setText(txtCoeficienteC.getValue().toString());
    }//GEN-LAST:event_txtCoeficienteCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BhaskaraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BhaskaraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BhaskaraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BhaskaraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BhaskaraTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCoeficienteA;
    private javax.swing.JLabel lblCoeficienteB;
    private javax.swing.JLabel lblCoeficienteC;
    private javax.swing.JLabel lblDelta;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JSpinner txtCoeficienteA;
    private javax.swing.JSpinner txtCoeficienteB;
    private javax.swing.JSpinner txtCoeficienteC;
    // End of variables declaration//GEN-END:variables
}
